### ISSUE TITLE
Running fakes instead of originals 

### ISSUE THREAD

**Issue by luky92** [ConnorBaxter/ScambaitToolkit#1]
You could write a simple agent program that swiches between normal and fake mode depending on  said mode it could kill original processes and start a fake one (that will be more tricky for fake tree and netcat but possibly doable

**Comment by ConnorBaxter** [comment]
That's possible but I think I'll implement this later on. At the minute the only program here that would want to be changed on the fly would probably be notepad. Once I've made further developments on further programs I'll come back to this and work out a smart way of doing it. Likely using hotkeys or a tray icon control.

**Comment by RealDoigt** [comment]
If you want, I can start working on it. I've made some research into it and I'm confident I can make a basic demo.

**Comment by ConnorBaxter** [comment]
Due to COVID I'm unable to work on this project for a while. If you'd like to work on this I'll accept the pull request. Thanks.
